### ISSUE TITLE
Where should the cff file go?

### ISSUE THREAD

**Issue by joelnitta** [dieghernan/cffr#36]
When I run `devtools::check()` on my package with a CFF file, I get this `note`:

```
❯ checking package subdirectories ... NOTE
  Found the following CITATION file in a non-standard place:
    CITATION.cff
  Most likely ‘inst/CITATION’ should be used instead.
```

However, I also see that this package includes `CITATION.cff` in the root directory. Is there somewhere else it should go to avoid this note but still have the citation info show up in github, etc?

**Comment by dieghernan** [comment]
Hi @joelnitta :

The CITATION.cff file shoud be on the root of your directory. Issue here is that you need also to add a .Rbuildignore file also on the root (if not already) with at least this line:

https://github.com/ropensci/cffr/blob/009f031e0958c4e7c118a561066f3329ec998b12/.Rbuildignore#L13

If you are creating your CITATION.cff with `cff_write()` this should be done automatically, see the docs:

https://docs.ropensci.org/cffr/reference/cff_write.html#details

> ## Details
> When creating and writing a CITATION.cff for the first time, the function adds "CITATION.cff" to ".Rbuildignore".

**Comment by dieghernan** [comment]
See also a list of R packages using `cffr` if you want to check its implementation. This packages itself is on CRAN with no errors or warnings following the setup described above

https://github.com/search?l=&o=desc&q=cffr+extension%3Acff+filename%3ACITATION&s=indexed&type=Code

**Comment by joelnitta** [comment]
Thanks, I forgot about .Rbuildignore! (I had actually created the cff file manually in this case).

You may want to add additional documentation about this somewhere, but fine with me if you want to close the issue now.

**Comment by dieghernan** [comment]
Closed. This is indeed documented and automatic for `cffr` users since the initial release
