### ISSUE TITLE
Crayon Package Superseded

### ISSUE THREAD

**Issue by aadler** [dieghernan/cffr#46]
It seems that the crayon package is [superseded](https://cran.r-project.org/web/packages/crayon/index.html). Is there intent that cffr will be ypdated to use the [cli](https://cran.r-project.org/web/packages/cli/) package as suggested there? Thank you.

**Comment by dieghernan** [comment]
I was not aware of that, thanks for letting me now.

I would switch to `cli` on the next release. However it seems that `crayon` would be still maintained, so I don't think `cffr` to be at risk soon.
