### ISSUE TITLE
Eat your own dog food?

### ISSUE THREAD

**Issue by IndrajeetPatil** [dieghernan/cffr#76]
I was looking for an example of `CITATION.cff` and came here, but was surprised to see that `{cffr}` package itself doesn't contain this file in its repo. I think it would be reassuring to include it 😉   

P.S. For the uninitiated, the issue title comes from https://en.wikipedia.org/wiki/Eating_your_own_dog_food

**Comment by dieghernan** [comment]
??? The file is here https://github.com/ropensci/cffr/blob/main/CITATION.cff

**Comment by IndrajeetPatil** [comment]
Oops, sorry about that. 

I swear I looked carefully, but I guess not carefully enough 🙈
